# Generated by Django 5.1.5 on 2025-01-19 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=150)),
                ('hotel_description', models.CharField(max_length=150)),
                ('hotel_email', models.CharField(max_length=100)),
                ('hotel_phone', models.CharField(max_length=100)),
                ('hotel_address', models.CharField(max_length=150)),
                ('hotel_rooms_number', models.IntegerField(default=0)),
                ('hotel_rooms_basic_price', models.IntegerField(default=100)),
                ('hotel_front_picture_url', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='date start')),
                ('end_date', models.DateTimeField(verbose_name='date end')),
                ('comments', models.CharField(max_length=500)),
                ('value', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('Hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.hotel')),
            ],
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_services',
            field=models.ManyToManyField(to='booking.service'),
        ),
    ]
