# Generated by Django 5.1.5 on 2025-01-22 15:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_reservationnew'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reservation',
            new_name='ReservationOLD',
        ),
    ]
