# Generated by Django 5.1.5 on 2025-01-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='hotel_front_picture',
            new_name='hotel_front_picture_url',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='services',
            new_name='hotel_services',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_servizi',
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_rooms_basic_price',
            field=models.IntegerField(default=100),
        ),
    ]
