# Generated by Django 5.1.5 on 2025-01-22 15:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_rename_reservation_reservationold'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReservationNew',
            new_name='Reservation',
        ),
    ]
