# Generated by Django 5.1.5 on 2025-01-22 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_rename_reservationnew_reservation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReservationOLD',
        ),
    ]
